<a href="https://colab.research.google.com/github/barbare03/Spaceship_Titanic/blob/main/Spaceship_Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [104]:
import pandas as pd
data = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Spaceship Titanic/train.csv")
test = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Spaceship Titanic/test.csv")
test_ids = test["PassengerId"]

##Preprocessing

In [105]:
data.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [106]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [107]:
data.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,8514.000000,8512.000000,8510.000000,8485.000000,8510.000000,8505.000000
mean,28.827930,224.687617,458.077203,173.729169,311.138778,304.854791
std,14.489021,666.717663,1611.489240,604.696458,1136.705535,1145.717189
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,47.000000,76.000000,27.000000,59.000000,46.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

In [108]:
data.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [109]:
round((data.isnull().sum() / data.shape[0]) * 100, 2)

PassengerId     0.00
HomePlanet      2.31
CryoSleep       2.50
Cabin           2.29
Destination     2.09
Age             2.06
VIP             2.34
RoomService     2.08
FoodCourt       2.11
ShoppingMall    2.39
Spa             2.11
VRDeck          2.16
Name            2.30
Transported     0.00
dtype: float64

In [110]:
data.duplicated().sum()

0

In [111]:
cat_col = [col for col in data.columns if data[col].dtype == 'object']
print('Categorical columns:', cat_col)
num_col = [col for col in data.columns if data[col].dtype != 'object']
print('Numerical columns:', num_col)

Categorical columns: ['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'VIP', 'Name']
Numerical columns: ['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'Transported']

In [112]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

cols = ['CryoSleep', 'VIP']
for col in cols:
  data[col] = le.fit_transform(data[col])
  test[col] = le.fit_transform(test[col])
  print(f"{col} classes:", le.classes_)

CryoSleep classes: [False True nan]
VIP classes: [False True nan]

In [113]:
def clean(data):
  cols_to_drop =['HomePlanet', 'Cabin', 'Destination', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'Name']
  data = data.drop([col for col in cols_to_drop if col in data.columns], axis=1)

  cols = ['CryoSleep', 'Age', 'VIP']
  for col in cols:
    data[col].fillna(data[col].median(), inplace=True)
  return data

data = clean(data)
test = clean(test)

<ipython-input-113-5e80fec20244>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
<ipython-input-113-5e80fec20244>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)

In [115]:
data.head()

  PassengerId  CryoSleep   Age  VIP  Transported
0     0001_01          0  39.0    0        False
1     0002_01          0  24.0    0         True
2     0003_01          0  58.0    1        False
3     0003_02          0  33.0    0        False
4     0004_01          0  16.0    0         True

##Training

In [116]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

y = data['Transported']
x = data.drop('Transported', axis=1)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [117]:
clf = LogisticRegression(random_state=0, max_iter=1000).fit(x_train, y_train)

In [118]:
predictions = clf.predict(x_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)

0.7153536515238643

In [119]:
submission_preds = clf.predict(test)

In [120]:
submission = pd.DataFrame({"PassengerId":test_ids.values,
                   "Transported": submission_preds,
                   })

In [121]:
submission.to_csv("/content/drive/My Drive/Colab Notebooks/Spaceship Titanic/submissions.csv", index=False)